# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_ldbtn_sw/zybo_ldbtn_sw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw || ORIG_REF_NAME==zybo_ldbtn_sw} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_processing_system7_0_0/zybo_ldbtn_sw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_processing_system7_0_0 || ORIG_REF_NAME==zybo_ldbtn_sw_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_axi_gpio_0_0/zybo_ldbtn_sw_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_axi_gpio_0_0 || ORIG_REF_NAME==zybo_ldbtn_sw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_axi_gpio_1_0/zybo_ldbtn_sw_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_axi_gpio_1_0 || ORIG_REF_NAME==zybo_ldbtn_sw_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_xbar_0/zybo_ldbtn_sw_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_xbar_0 || ORIG_REF_NAME==zybo_ldbtn_sw_xbar_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_auto_pc_0/zybo_ldbtn_sw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_auto_pc_0 || ORIG_REF_NAME==zybo_ldbtn_sw_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_ps7_0_axi_periph_0/zybo_ldbtn_sw_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_ldbtn_sw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_ldbtn_sw_rst_ps7_0_100M_0 || ORIG_REF_NAME==zybo_ldbtn_sw_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/zybo_ldbtn_sw/zybo_ldbtn_sw_ooc.xdc
