# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0.xci
# IP: The module: 'zybo_ldbtn_sw_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0.xci
# IP: The module: 'zybo_ldbtn_sw_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/lab08_freertos_software_timer/lab08_freertos_software_timer.srcs/sources_1/bd/zybo_ldbtn_sw/ip/zybo_ldbtn_sw_rst_ps7_0_100M_0/zybo_ldbtn_sw_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_ldbtn_sw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
